DocumentRoot "C:/karaoke"

<Directory "C:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "C:/bgv/"
<Directory "C:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "C:/bgv"
SetEnv DOC_ROOT "C:/karaoke"