DocumentRoot "H:/karaoke"

<Directory "H:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "H:/bgv/"
<Directory "H:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "H:/bgv"
SetEnv DOC_ROOT "H:/karaoke"