DocumentRoot "G:/karaoke"

<Directory "G:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "G:/bgv/"
<Directory "G:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "G:/bgv"
SetEnv DOC_ROOT "G:/karaoke"