LoadModule access_compat_module modules/mod_access_compat.so
LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule include_module modules/mod_include.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule headers_module modules/mod_headers.so

Listen 80
Timeout 600
TypesConfig conf/mime.types
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz

ServerAdmin webmaster@mochikara.local
ServerName www.mochikara2.local:80
DirectoryIndex index.html

<Directory />
    Options Indexes
    Require all granted
</Directory>

<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
LogLevel warn

# added for mochikara2

ServerRoot "C:/mochikara2/Apache24"
Include conf/httpd-mochikara.conf

ScriptAlias /cgi-bin/ "C:/mochikara2/cgi-bin/"
<Directory "C:/mochikara2/cgi-bin">
    Options +ExecCGI -Indexes
    AllowOverride None
    Require all granted
    AddHandler cgi-script .py
</Directory>

Alias /htdocs/ "C:/mochikara2/htdocs/"
<Directory "C:/mochikara2/htdocs">
    Options Includes
    Require all granted
    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml
</Directory>

ErrorLog "../tmp/error.log"
CustomLog "../tmp/access.log" common

Action video/mp4 /cgi-bin/mochi2_mpc.py
Action video/mpeg /cgi-bin/mochi2_mpc.py
Action video/x-msvideo /cgi-bin/mochi2_mpc.py
Action video/x-ms-wmv /cgi-bin/mochi2_mpc.py
Action video/x-flv /cgi-bin/mochi2_mpc.py
Action video/x-matroska /cgi-bin/mochi2_mpc.py
Action audio/mpeg /cgi-bin/mochi2_mpc.py

IndexOptions FancyIndexing HTMLTable VersionSort NameWidth=* FoldersFirst SuppressDescription SuppressLastModified
Alias /icons/ "C:/mochikara2/Apache24/icons/"
<Directory "C:/mochikara2/Apache24/icons">
    Options Indexes
</Directory>
AddIconByType (IMG,/icons/image2.gif) image/*
AddIconByType (SND,/icons/sound2.gif) audio/*
AddIconByType (VID,/icons/movie.gif) video/*
AddIcon /icons/back.gif ..
AddIcon /icons/hand.right.gif README
AddIcon /icons/folder.gif ^^DIRECTORY^^
AddIcon /icons/blank.gif ^^BLANKICON^^
DefaultIcon /icons/unknown.gif
IndexIgnore *.txt *.bat *.ass *.ssa *.htm *.pl *.exe *.lnk *.msi *.conf *.db *.BIN *.tmp *.ffs_db *.csv *.smi *.kra *.lrc *.mp2 *.swf *.wav *.ico *.ini
IndexStyleSheet /htdocs/mochi2_fancy2.css
HeaderName /htdocs/mochi2_HEADER.shtml
ReadmeName /htdocs/mochi2_README.shtml

SetEnv MPC_PATH "C:/mochikara2/MPC-BE/mpc-be64.exe"

# mochikara2 flag
SetEnv INTERMISSION ON
SetEnv TRACK_CHG ON
SetEnv KEY_CHG OFF

# css/js no-cache
IndexHeadInsert "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Cache-Control\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">"
<FilesMatch "\.(css|js)$">
    Header set Cache-Control "no-cache"
</FilesMatch>
