DocumentRoot "E:/karaoke"

<Directory "E:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "E:/bgv/"
<Directory "E:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "E:/bgv"
SetEnv DOC_ROOT "E:/karaoke"