DocumentRoot "D:/karaoke"

<Directory "D:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "D:/bgv/"
<Directory "D:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "D:/bgv"
SetEnv DOC_ROOT "D:/karaoke"