DocumentRoot "I:/karaoke"

<Directory "I:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "I:/bgv/"
<Directory "I:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "I:/bgv"
SetEnv DOC_ROOT "I:/karaoke"