DocumentRoot "F:/karaoke"

<Directory "F:/karaoke">
    Options Indexes
    Require all granted
</Directory>

Alias /bgv/ "F:/bgv/"
<Directory "F:/bgv">
    Options Indexes
    Require all granted
</Directory>

SetEnv BGV_PATH "F:/bgv"
SetEnv DOC_ROOT "F:/karaoke"