# mochikara2.ini もちからWeb^2の定義、適宜修正してください
[wifi]
# スタート動画で表示する接続先
ssid=ikara
passwd=
ipaddr=192.168.137.1
# QRコードを再生成するか否か
makeqr=off
[topic]
# 本日のトピック、2行まで
1=もちからWeb^2 システム更改！
2=まずはいろいろ触って試してみてくださいな
[mochikomi]
# 持込フォルダ作成メンバ、member5まで
member1=
member2=
member3=
member4=
member5=
